<div id="section2" class="landing-section skt-section skt-default-page">
	<div class="container" >
		<div class="row-fluid">
			<div class="span12">
				<div class="title custicon"><p class="landing-section-heading"><?php echo wp_kses_post( get_theme_mod('connexions_lite_rat_second_section_title', __('ABOUT US', 'connexions-lite') ) ); ?></p><div class="title-border"><i class="fa fa-bullseye"></i></div></div>
				<div class="landing-page-content">
					<?php echo do_shortcode( wp_kses_post( get_theme_mod('connexions_lite_rat_second_section_content', '<div class="skepost clearfix text-center"><div class="inner_pages_content">'.__('Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', 'connexions-lite').'</div><div class="page-container clearfix"><div class="con-key-feature span3 skt_animate_when_almost_visible small-to-large skt_start_animation"><div class="con-icon-wrap"><div class="con-feature-icon"><i class="fa fa-desktop"></i></div></div><div class="con-icon-title">'.__('WE ARE CREATIVE','connexions-lite').'</div><div class="con-icon-desc">'.__('Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard', 'connexions-lite').'</div></div><div class="con-key-feature span3 skt_animate_when_almost_visible small-to-large skt_start_animation"><div class="con-icon-wrap"><div class="con-feature-icon"><i class="fa fa-eye"></i></div></div><div class="con-icon-title">'.__('WE ARE COLL NERDS', 'connexions-lite').'</div><div class="con-icon-desc">'.__('Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard', 'connexions-lite').'</div></div><div class="con-key-feature span3 skt_animate_when_almost_visible small-to-large skt_start_animation"><div class="con-icon-wrap"><div class="con-feature-icon"><i class="fa fa-cogs"></i></div></div><div class="con-icon-title">'.__('WE ARE PASSIONATE', 'connexions-lite').'</div><div class="con-icon-desc">'.__('Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard', 'connexions-lite').'</div></div><div class="con-key-feature span3 skt_animate_when_almost_visible small-to-large skt_start_animation"><div class="con-icon-wrap"><div class="con-feature-icon"><i class="fa fa-code"></i></div></div><div class="con-icon-title">'.__('WE ARE INNOVATIVE', 'connexions-lite').'</div><div class="con-icon-desc">'.__('Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard', 'connexions-lite').'</div></div></div></div>') ) ); ?>
				</div>
			</div>
		</div>
	</div>
</div>