<?php
/*
Plugin Name: My Custom CSS
Plugin URI: https://wordpress.org/plugins/my-custom-css/
Description: With this plugin you can put custom css code without edit your theme and/or your plugins (really useful in case of any theme/plugin update).
It contain also <a href="https://ace.c9.io/">Ace (Ajax.org Cloud9 Editor)</a> Code Editor for write a good css code.
You can see in action (source code) here: <a href="http://www.vegamami.it/">VegAmami</a> :)
PS: support file backup and - very important - static css file (fantastic for performance) ;)
Author: DarkWolf
Version: 3.0
Author URI: https://laltroweb.it/
Text Domain: my-custom-css
*/

/* To prevent PHP errors */
if (!defined('DB_NAME'))
{
	header( ( isset( $_SERVER['SERVER_PROTOCOL'] ) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.0' ) . ' 403 Forbidden' );
	exit;
}

// Text Domain: my-custom-css
load_plugin_textdomain('my-custom-css', false, dirname(plugin_basename(__FILE__)) . '/lang/');

// Generate basedir and baseurl
function plugin_basedir() {	$upload_dir = wp_upload_dir(); $plugin_basedir = $upload_dir['basedir']; return $plugin_basedir; }
function plugin_url() {	$upload_dir = wp_upload_dir(); $plugin_url = set_url_scheme($upload_dir['baseurl']); return $plugin_url; }

// Generate my_style_id url:
function my_style_id() { $blog_id = get_current_blog_id(); $cssid = ( $blog_id > "1" ) ? $cssid = "_id-".$blog_id : $cssid = null; $my_style_id = "/my_custom_css/my_style".$cssid.".css"; return $my_style_id; }

// Generate css url and css path
function css_url() { $css_url = plugin_url().my_style_id();	return $css_url; }
function css_path() { $css_path = plugin_basedir().my_style_id(); return $css_path; }

// make my_style.css and write write css code!
function getdata() { $getdata = strip_tags(get_option('my_custom_css')); return $getdata; }

// Write in source!
function mycustomcss_head()
{
	$data = getdata();
	if (!empty($data))
	{
		echo "\n<!-- My Custom CSS -->\n<link rel='stylesheet' id='mccss_stylesheet' href='".css_url()."?".@filemtime(css_path())."' type='text/css' media='all' />\n<!-- My Custom CSS -->\n";
	}
}

// Make css file
function makecss()
{
	$makecss = file_put_contents(css_path(), "/******* Do not edit this file *******/\n/*\nMy Custom CSS - by Salvatore Noschese\naka L'AltroWeb - https://laltroweb.it/\n/*\nSaved: ".date("M d Y | h:i:s (a)",current_time('timestamp'))."\n/*\n/******* Do not edit this file *******/\n\n".getdata());
	return $makecss;
}

// Fix first upgrade from old release or manual my_style.css deletion!
if (!file_exists(css_path()) || isset($_POST['save'])) { makecss(); }

// Fix old backup folder or no exist
if (!is_dir(plugin_basedir().'/my_custom_css/bkk')) { wp_mkdir_p(plugin_basedir().'/my_custom_css/bkk'); }
// And Blank index.php to prevent listing directory
else if(!file_exists(plugin_basedir()."/my_custom_css/index.php") || !file_exists(plugin_basedir()."/my_custom_css/bkk/index.php"))
{ file_put_contents(plugin_basedir()."/my_custom_css/index.php", "<?php \n// Prevent Directory Listing..."); file_put_contents(plugin_basedir()."/my_custom_css/bkk/index.php", "<?php \n// Prevent Directory Listing..."); }

// Start Add link on plugins page
function mycustomcss_links($links)
{ 
	# Settings:
	$settings_link = '<a href="admin.php?page=my_custom_css" title="My Custom CSS">'.__('Settings','my-custom-css').'</a>';
	array_unshift($links, $settings_link);
	# Support:
	$support_forum = '<a href="https://laltroweb.it/" title="laltroweb.it">'.__('Support','my-custom-css').'</a>';
	array_unshift($links, $support_forum);
	# return:
	return $links;
}
function add_plugin_meta_links($links, $file)
{
	if ($file == plugin_basename(__FILE__))
	{
		$links[] = '<a href="https://www.paypal.me/SalvatoreN" title="Buy Me a Beer ;)">Donate &#128522;</a>';
	}
	return $links;
}

function mccss_png()
{
	$mccss_png = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAnFBMVEUAAAAAAABuRSAAAADJgjl3TCIAAADOgj3Ifjb/////qg//2IP/tSj/rRf/68LHfTT/uTH/siAqfQD/783/zFnI8E7/xk7/vjg6iQAvgQD/0W7/zlP/wkLbgEG/60CdxwAziAD/3IT/0Wf/z1rM8VjPfjul4gCi2ACd0gBJigBDhwD/6bz/1Xv/1Hr/zWP/1l3H7k2gzwCbwACatQA6TvqRAAAACHRSTlMACVkz8F4v8dedY+EAAACsSURBVBjTVY7ZDoIwEAAXq9jFAqXc93166///mwWMkUlmk53sw8KebtgDLU9/lBToRZPoX68UzOiMaOgG4mxkgnlDTUddjtlIXjhoMWahYc1WS2Ccc2YgYzZW7RIYci71fRGmQB0b0fYXhdsEQOvESxJPCM8TzduV4R7HcR26jzB0X3mRrq+3RZZnWf4s0iOoh91M0A9DH+wOKoCyQKaum4iiwA8yjgQ2kHX/AB8tDwIctw6nAAAAAElFTkSuQmCC";
	return $mccss_png;
}
// Change the CSS for this plugin on admin plugins page
function mycustomcss_admin_style()
{
	global $pagenow;
	if ($pagenow == "plugins.php")
	{
		echo "<style type='text/css'>\n#my-custom-css td.plugin-title strong {\n\tbackground: url(".mccss_png().") no-repeat scroll 115px 2px;\n}\n#my-custom-css div.row-actions-visible {\n\tpadding-top: 15px;\n}\n#my-custom-css div.plugin-version-author-uri {\n\tbackground-color: #EAEAEA;\n\tborder-radius: 5px;\n\tbox-shadow: 0 8px 6px -6px gray; \n\tfont-weight: bold; \n\tpadding: 7px; \n\tmargin-bottom: 12px;\n}\n</style>\n";
	}
}

// Get plugin version
function plug_ver()
{
	$plugin_data = get_plugin_data(__FILE__);
	$plug_ver = $plugin_data['Version'];
	return $plug_ver;
}
// Get plugin title
function plug_name()
{
	$plugin_data = get_plugin_data(__FILE__);
	$plug_name = $plugin_data['Name'];
	return $plug_name;
}

// Set Theme
function thl()
{
	if(isset($_POST["themelist"]))
	{
		$thl = $_POST["themelist"];
		return $thl;
	}
}
$thl = thl();
if (isset($thl) && !empty($thl))
{
	setcookie('_mccss_ace_themelist_', $thl, time()+31556926 ,'/');
}
function sth()
{
	$thl = thl();
	if (isset($thl) && !empty($thl))
	{
		$sth = $thl;
	}
	else if (!isset($_COOKIE['_mccss_ace_themelist_']))
	{
		$sth = 'ace/theme/textmate';
	}
	else
	{
		$sth = $_COOKIE['_mccss_ace_themelist_'];
	}
	return $sth;
}

// Set Invisibles
function enable_invisibles()
{	
	if(!isset($_POST['invisibles']) && empty($_POST['invisibles']) && isset($_COOKIE['_mccss_enable_invisibles_']))
	{
		$invisibles = $_COOKIE['_mccss_enable_invisibles_'];
	}
	else if(isset($_POST['invisibles']) && !empty($_POST['invisibles']) && $_COOKIE['_mccss_enable_invisibles_'] === "false")
	{
		$invisibles = "true";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else if(isset($_POST['invisibles']) && !empty($_POST['invisibles']) && $_COOKIE['_mccss_enable_invisibles_'] === "true")
	{
		$invisibles = "false";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else
	{
		$invisibles = "false";
	}
	return $invisibles;
}

// Set Margin
function enable_margin()
{	
	if(!isset($_POST['margin']) && empty($_POST['margin']) && isset($_COOKIE['_mccss_enable_margin_']))
	{
		$margin = $_COOKIE['_mccss_enable_margin_'];
	}
	else if(isset($_POST['margin']) && !empty($_POST['margin']) && $_COOKIE['_mccss_enable_margin_'] === "false")
	{
		$margin = "true";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else if(isset($_POST['margin']) && !empty($_POST['margin']) && $_COOKIE['_mccss_enable_margin_'] === "true")
	{
		$margin = "false";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else
	{
		$margin = "false";
	}
	return $margin;
}

// Set LineNumbers
function enable_linenumbers()
{	
	if(!isset($_POST['linenumbers']) && empty($_POST['linenumbers']) && isset($_COOKIE['_mccss_enable_linenumbers_']))
	{
		$linenumbers = $_COOKIE['_mccss_enable_linenumbers_'];
	}
	else if(isset($_POST['linenumbers']) && !empty($_POST['linenumbers']) && $_COOKIE['_mccss_enable_linenumbers_'] === "false")
	{
		$linenumbers = "true";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else if(isset($_POST['linenumbers']) && !empty($_POST['linenumbers']) && $_COOKIE['_mccss_enable_linenumbers_'] === "true")
	{
		$linenumbers = "false";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else
	{
		$linenumbers = "true";
	}
	return $linenumbers;
}

// Set disablebackup
function enable_backup()
{	
	if(!isset($_POST['disablebackup']) && empty($_POST['disablebackup']) && isset($_COOKIE['_mccss_enable_backup_']))
	{
		$disablebackup = $_COOKIE['_mccss_enable_backup_'];
	}
	else if(isset($_POST['disablebackup']) && !empty($_POST['disablebackup']) && $_COOKIE['_mccss_enable_backup_'] === "false")
	{
		$disablebackup = "true";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else if(isset($_POST['disablebackup']) && !empty($_POST['disablebackup']) && $_COOKIE['_mccss_enable_backup_'] === "true")
	{
		$disablebackup = "false";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else
	{
		$disablebackup = "true";
	}
	return $disablebackup;
}

// Set basicautocomplete
function enable_autocomplete()
{	
	if(!isset($_POST['basicautocomplete']) && empty($_POST['basicautocomplete']) && isset($_COOKIE['_mccss_enable_autocomplete_']))
	{
		$basicautocomplete = $_COOKIE['_mccss_enable_autocomplete_'];
	}
	else if(isset($_POST['basicautocomplete']) && !empty($_POST['basicautocomplete']) && $_COOKIE['_mccss_enable_autocomplete_'] === "false")
	{
		$basicautocomplete = "true";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else if(isset($_POST['basicautocomplete']) && !empty($_POST['basicautocomplete']) && $_COOKIE['_mccss_enable_autocomplete_'] === "true")
	{
		$basicautocomplete = "false";
		header('location: '.$_SERVER['REQUEST_URI'].'');
	}
	else
	{
		$basicautocomplete = "true";
	}
	return $basicautocomplete;
}

// Option page code:
function mycustomcss_scripts()
{
	echo '
	<!-- Start My Custom CSS Code -->
	<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/_scrolltop.js?plug_ver='.plug_ver().'"></script>';
	if(!isset($_POST['viewbackup']) && !isset($_POST['erasebackup']))
	{
	echo '
	<!-- Ace Editor -->
	<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/ace.js?plug_ver='.plug_ver().'" charset="utf-8"></script>
	<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/ext-searchbox.js?plug_ver='.plug_ver().'" charset="utf-8"></script>
	<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/ext-language_tools.js?plug_ver='.plug_ver().'" charset="utf-8"></script>
	<script type="text/javascript">
	// Ace Setting
	( function( global, $ ) {
		var editor,
			syncCSS = function() {
				$("#my_custom_css_textarea").val(editor.getSession().getValue());
			},
			loadAce = function() {
				editor = ace.edit("my_custom_css");
				global.safecss_editor = editor;
				editor.session.setMode("ace/mode/css");
				editor.$blockScrolling = Infinity;
				editor.getSession().setUseWrapMode(true);
				editor.getSession().setValue($("#my_custom_css_textarea").val());
				editor.getSession().setUseSoftTabs(true);
				editor.setHighlightActiveLine(true);
				editor.setOptions({minLines: 10});
				editor.setOptions({maxLines: Infinity});
				editor.setTheme("'.sth().'");
				editor.setOption("firstLineNumber", 1)
				editor.setShowPrintMargin('.enable_margin().');
				editor.setShowInvisibles('.enable_invisibles().');
				editor.setOption("showLineNumbers", '.enable_linenumbers().');
				editor.execCommand("find");
				// enable autocompletion and snippets
				ace.require("ace/ext/language_tools");
					editor.setOptions({
					enableBasicAutocompletion: '.enable_autocomplete().',
					enableSnippets: '.enable_autocomplete().',
					enableLiveAutocompletion: '.enable_autocomplete().'
				});
				jQuery.fn.spin&&$("#my_custom_css_container").spin(false);
				$("#my-custom-css").submit(syncCSS);
			};
		if ($.browser.msie&&parseInt($.browser.version, 10) <= 7) {
			$("#my_custom_css_container").hide();
			$("#my_custom_css_textarea").show();
			return false;
		} else {
			$(global).load(loadAce);
		}
		global.aceSyncCSS = syncCSS;
	} )(this, jQuery);
	</script>
	<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/textresizer/cookie.js?plug_ver='.plug_ver().'"></script>
	<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/textresizer/textresizer.min.js?plug_ver='.plug_ver().'"></script>
	<script type="text/javascript" src="'.plugin_dir_url(__FILE__).'editor/textresizer/textresizer_target.js?plug_ver='.plug_ver().'"></script>';
	}
	echo '
	<!-- CSS Code -->
	<link rel="stylesheet" id="ace-editor-custom-css" href="'.plugin_dir_url(__FILE__).'editor/ace_custom.css?plug_ver='.plug_ver().'" type="text/css" media="all" />
	<!-- End My Custom CSS Code -->';
}

// Textarea/Form:
function mccss_admin_page()
{
	echo '
	<div class="wrap">';
		if(!isset($_POST['viewbackup']) && !isset($_POST['erasebackup']))
		{
			$at = "ace/theme/";
			// BrightTheme
			$b1 = $at."chrome";
			$b2 = $at."clouds";
			$b3 = $at."crimson_editor";
			$b4 = $at."dawn";
			$b5 = $at."dreamweaver";
			$b6 = $at."eclipse";
			$b7 = $at."github";
			$b8 = $at."iplastic";
			$b9 = $at."solarized_light";
			$b10 = $at."textmate";
			$b11 = $at."tomorrow";
			$b12 = $at."xcode";
			$b13 = $at."kuroir";
			$b14 = $at."katzenmilch";
			$b15 = $at."sqlserver";
			// DarkTheme
			$d1 = $at."ambiance";
			$d2 = $at."chaos";
			$d3 = $at."clouds_midnight";
			$d4 = $at."cobalt";
			$d5 = $at."idle_fingers";
			$d6 = $at."kr_theme";
			$d7 = $at."merbivore";
			$d8 = $at."merbivore_soft";
			$d9 = $at."mono_industrial";
			$d10 = $at."monokai";
			$d11 = $at."pastel_on_dark";
			$d12 = $at."solarized_dark";
			$d13 = $at."terminal";
			$d14 = $at."tomorrow_night";
			$d15 = $at."tomorrow_night_blue";
			$d16 = $at."tomorrow_night_bright";
			$d17 = $at."tomorrow_night_eighties";
			$d18 = $at."twilight";
			$d19 = $at."vibrant_ink";
			echo '
			<h2>' .  __('My Custom CSS Panel','my-custom-css') . ' - v'.plug_ver().'</h2>
			<div id="tools">
				<div id="text-resizer">
					<p>' .  __('Font:','my-custom-css') . '</p>
						<ul class="textresizer">
						  <li><a href="#nogo" class="small-text" title="12px (Small)">A-</a></li>
						  <li><a href="#nogo" class="medium-text" title="14px (Medium)">A</a></li>
						  <li><a href="#nogo" class="large-text" title="16px (Large)">A+</a></li>
						  <li><a href="#nogo" class="larger-text" title="18px (Larger)">A++</a></li>
						  <li><a href="#nogo" class="giga-text" title="26px (Giga)">A+++</a></li>
						</ul>
				</div>
				<form action="" method="post" id="thememenu">
					<label for="theme">' .  __('Theme:','my-custom-css') . '</label>
						<select name="themelist" id="themelist" onchange="if(confirm(\'' .  __('Warning!!! This will refresh entire page (Unsaved data will be lost) - Continue?','my-custom-css') . '\')){this.form.submit()}">
							<optgroup label="' .  __('Bright:','my-custom-css') . '">
								<option value="'.$b1.'"'.(sth() == $b1 ? ' selected="selected"' : false).'>Chrome</option>
								<option value="'.$b2.'"'.(sth() == $b2 ? ' selected="selected"' : false).'>Clouds</option>
								<option value="'.$b3.'"'.(sth() == $b3 ? ' selected="selected"' : false).'>Crimson Editor</option>
								<option value="'.$b4.'"'.(sth() == $b4 ? ' selected="selected"' : false).'>Dawn</option>
								<option value="'.$b5.'"'.(sth() == $b5 ? ' selected="selected"' : false).'>Dreamweaver</option>
								<option value="'.$b6.'"'.(sth() == $b6 ? ' selected="selected"' : false).'>Eclipse</option>
								<option value="'.$b7.'"'.(sth() == $b7 ? ' selected="selected"' : false).'>GitHub</option>
								<option value="'.$b8.'"'.(sth() == $b8 ? ' selected="selected"' : false).'>IPlastic</option>
								<option value="'.$b9.'"'.(sth() == $b9 ? ' selected="selected"' : false).'>Solarized Light</option>
								<option value="'.$b10.'"'.(sth() == $b10 ? ' selected="selected"' : false).'>TextMate</option>
								<option value="'.$b11.'"'.(sth() == $b11 ? ' selected="selected"' : false).'>Tomorrow</option>
								<option value="'.$b12.'"'.(sth() == $b12 ? ' selected="selected"' : false).'>XCode</option>
								<option value="'.$b13.'"'.(sth() == $b13 ? ' selected="selected"' : false).'>Kuroir</option>
								<option value="'.$b14.'"'.(sth() == $b14 ? ' selected="selected"' : false).'>KatzenMilch</option>
								<option value="'.$b15.'"'.(sth() == $b15 ? ' selected="selected"' : false).'>SQL Server</option>
							</optgroup>
							<optgroup label="' .  __('Dark:','my-custom-css') . '">
								<option value="'.$d1.'"'.(sth() == $d1 ? ' selected="selected"' : false).'>Ambiance</option>
								<option value="'.$d2.'"'.(sth() == $d2 ? ' selected="selected"' : false).'>Chaos</option>
								<option value="'.$d3.'"'.(sth() == $d3 ? ' selected="selected"' : false).'>Clouds Midnight</option>
								<option value="'.$d4.'"'.(sth() == $d4 ? ' selected="selected"' : false).'>Cobalt</option>
								<option value="'.$d5.'"'.(sth() == $d5 ? ' selected="selected"' : false).'>idle Fingers</option>
								<option value="'.$d6.'"'.(sth() == $d6 ? ' selected="selected"' : false).'>krTheme</option>
								<option value="'.$d7.'"'.(sth() == $d7 ? ' selected="selected"' : false).'>Merbivore</option>
								<option value="'.$d8.'"'.(sth() == $d8 ? ' selected="selected"' : false).'>Merbivore Soft</option>
								<option value="'.$d9.'"'.(sth() == $d9 ? ' selected="selected"' : false).'>Mono Industrial</option>
								<option value="'.$d10.'"'.(sth() == $d10 ? ' selected="selected"' : false).'>Monokai</option>
								<option value="'.$d11.'"'.(sth() == $d11 ? ' selected="selected"' : false).'>Pastel on dark</option>
								<option value="'.$d12.'"'.(sth() == $d12 ? ' selected="selected"' : false).'>Solarized Dark</option>
								<option value="'.$d13.'"'.(sth() == $d13 ? ' selected="selected"' : false).'>Terminal</option>
								<option value="'.$d14.'"'.(sth() == $d14 ? ' selected="selected"' : false).'>Tomorrow Night</option>
								<option value="'.$d15.'"'.(sth() == $d15 ? ' selected="selected"' : false).'>Tomorrow Night Blue</option>
								<option value="'.$d16.'"'.(sth() == $d16 ? ' selected="selected"' : false).'>Tomorrow Night Bright</option>
								<option value="'.$d17.'"'.(sth() == $d17 ? ' selected="selected"' : false).'>Tomorrow Night 80s</option>
								<option value="'.$d18.'"'.(sth() == $d18 ? ' selected="selected"' : false).'>Twilight</option>
								<option value="'.$d19.'"'.(sth() == $d19 ? ' selected="selected"' : false).'>Vibrant Ink</option>
							</optgroup>
						</select>
				</form>';
				// Hidden view/erase button for blog id > 1 (security fix in multisite)
				if(get_current_blog_id() == 1 && enable_backup() === "true")
				{
					// If no backup exist, disable button!
					$glob = glob(plugin_basedir()."/my_custom_css/bkk/*.css");
					if ($glob == false)
					{
						$submit_backup = 'value="' .  __('No backup found','my-custom-css') . '" title="' .  __('No backup found','my-custom-css') . '" disabled="disabled" class="button-secondary"';
					}
					else
					{
						$submit_backup = 'value="' .  __('View backups','my-custom-css') . '" title="' .  __('Click to view all backups!','my-custom-css') . '" class="button"';
					}
					echo '
					<form id="backup" method="post" action="'.admin_url( 'admin.php' ).'?page=my_custom_css">
						<label for="backup">' .  __('Backup:','my-custom-css') . '</label>
						<input type="submit" name="viewbackup" '.$submit_backup.' />
					</form>';
				}
			$enable = __('Enable','my-custom-css');
			$disable = __('Disable','my-custom-css');			
			echo '
			<p><a href="#" onclick="jQuery(\'#advanced\').toggle();" id="toggle">' .  __('Advanced','my-custom-css') . ' &#x21D5;</a></p>
			<div id="advanced">
				<form action="" method="post" id="invisibles">
					<label for="invisibles">'.(enable_invisibles() == "false" ? ''.$enable.'' : ''.$disable.'').'/' .  __('Invisibles','my-custom-css') . '</label>
					<Input type="radio" name="invisibles" onchange="if(confirm(\'' .  __('Warning!!! This will refresh entire page (Unsaved data will be lost) - Continue?','my-custom-css') . '\')){this.form.submit()}" value="'.enable_invisibles().'" />
				</form>
				<form action="" method="post" id="margin">
					<label for="margin">'.(enable_margin() == "false" ? ''.$enable.'' : ''.$disable.'').'/' .  __('Margin','my-custom-css') . '</label>
					<Input type="radio" name="margin" onchange="if(confirm(\'' .  __('Warning!!! This will refresh entire page (Unsaved data will be lost) - Continue?','my-custom-css') . '\')){this.form.submit()}" value="'.enable_margin().'" />
				</form>
				<form action="" method="post" id="linenumbers">
					<label for="linenumbers">'.(enable_linenumbers() == "false" ? ''.$enable.'' : ''.$disable.'').'/' .  __('LineNumbers','my-custom-css') . '</label>
					<Input type="radio" name="linenumbers" onchange="if(confirm(\'' .  __('Warning!!! This will refresh entire page (Unsaved data will be lost) - Continue?','my-custom-css') . '\')){this.form.submit()}" value="'.enable_linenumbers().'" />
				</form>
				<form action="" method="post" id="disablebackup">
					<label for="disablebackup">'.(enable_backup() == "false" ? ''.$enable.'' : ''.$disable.'').'/' .  __('Backup','my-custom-css') . '</label>
					<Input type="radio" name="disablebackup" onchange="if(confirm(\'' .  __('Warning!!! This will refresh entire page (Unsaved data will be lost) - Continue?','my-custom-css') . '\')){this.form.submit()}" value="'.enable_backup().'" />
				</form>
				<form action="" method="post" id="basicautocomplete">
					<label for="basicautocomplete">'.(enable_autocomplete() == "false" ? ''.$enable.'' : ''.$disable.'').'/' .  __('Autocomplete','my-custom-css') . '</label>
					<Input type="radio" name="basicautocomplete" onchange="if(confirm(\'' .  __('Warning!!! This will refresh entire page (Unsaved data will be lost) - Continue?','my-custom-css') . '\')){this.form.submit()}" value="'.enable_autocomplete().'" />
				</form>
			</div>
			</div>
			<div id="my_custom_css_container">
				<form id="my-custom-css" method="post" action="options.php">';
				settings_fields( 'mccss_settings' );
				echo '
					<div name="my_custom_css" id="my_custom_css"></div>
<!-- start textarea -->
<textarea id="my_custom_css_textarea" name="my_custom_css" style="display: none;">'.get_option('my_custom_css').'</textarea>
<!-- end textarea -->
					<input type="submit" name="save" class="button-primary" value="' .  __("Save","my-custom-css") . '" />
				</form>
			</div>';
		}

		// View backup (view only css)
		else if(isset($_POST['viewbackup']))
		{
			date_default_timezone_set(ini_get('date.timezone') ? ini_get('date.timezone') : 'UTC');
			$bd = plugin_basedir()."/my_custom_css/bkk/";
			$files=array();
			if ($dh=opendir($bd))
			{
				while (($file=readdir($dh))!==false)
				if ($file!="." && $file!=".." && preg_match("/\.(css)$/", $file))
					$files[filemtime($bd.$file)]=$file;
				closedir($dh);
			}
			krsort($files);
			reset($files);
			$href = plugin_url()."/my_custom_css/bkk/";
			echo '
				<h2 id="h2left">' .  __('My custom CSS - Backup','my-custom-css') . '</h2>
				<form method="post" id="erase" action="">
					<input type="button" class="button" value="' .  __('Close now!','my-custom-css') . '" onclick="location.reload();" />
					 | 
					<input type="submit" class="button-primary" name="erasebackup" value="' .  __('Erase all backup?','my-custom-css') . '" onclick="return confirm(\'' .  __('Do you want really delete all backup?','my-custom-css') . '\');" />
				</form>
				<br />';
			while (list($date,$file)=each($files))
			echo '
				<div class="backup_list">
					<p><b>' .  __('File:','my-custom-css') . '</b> <a href="'.$href.$file.'">'.$href.$file.'</a></p>
					<p><b>' .  __('Path:','my-custom-css') . '</b> '.$bd.$file.'</p>
					<p><b>' .  __('Saved:','my-custom-css') . '</b> '.date("M d Y | h:i:s (a)",current_time($date)).'</p>
					<p><b>' .  __('Size:','my-custom-css') . '</b> '.(round(filesize($bd.$file). " bytes")).' bytes</p>
				</div>';
		}

		// Erase backup:
		else if(isset($_POST['erasebackup']))
		{
		echo '
			<h2 id="h2left">' .  __('My custom CSS - Erase Backup','my-custom-css') . '</h2>
				<input type="button" class="button-primary" id="close" value="' .  __('Close now!','my-custom-css') . '" onclick="location.reload();" />
			<br />';
			foreach (glob(plugin_basedir()."/my_custom_css/bkk/*.css") as $filename)
			{
			echo '
				<div class="backup_list">
					'.$filename.' - ' . filesize($filename) . '' .  __('bytes, was successfully deleted!!!','my-custom-css') . '
				</div>';
				unlink($filename);
			}
		}
		echo '
		<div id="mccss_credit">
			<a href="https://wordpress.org/plugins/my-custom-css/" title="My Custom CSS">My Custom CSS v'.plug_ver().'</a> | Author: <a href="https://laltroweb.it/" title="Salvatore Noschese - (L\'AltroWeb)">Salvatore Noschese</a> - Support my work: <a href="https://www.paypal.me/SalvatoreN" title="Even 1$ can help... :)">Donate &#128522;</a>
		</div>
		<!-- Smooth Scroll --><a href="#" class="scrollup">&#9650;</a><!-- Smooth Scroll -->
	</div>';
}


// Make backup when save!
$data = getdata();
if(isset($_POST['save']) && !empty($data) && enable_backup() === "true")
{
	$directory = plugin_basedir()."/my_custom_css/bkk/*.css";
	if (glob($directory) != false)
	{
		$filecount = count(glob($directory))+1;
	}
	else
	{
		$filecount = 1;
	}
	$oldname = css_path();
	$newname = plugin_basedir().'/my_custom_css/bkk/' . ( $filecount ++ ) . $cssid . '_' . filemtime($oldname) .'.css';
	rename($oldname, $newname);
}

// Register Settings
function mycustomcss_registersetting()
{	
	// Set cookie only if can manage plugin
	if ( current_user_can( 'manage_options' ) )
	{
		setcookie('_mccss_enable_invisibles_', enable_invisibles(), time()+31556926 ,'/');
		setcookie('_mccss_enable_margin_', enable_margin(), time()+31556926 ,'/');
		setcookie('_mccss_enable_linenumbers_', enable_linenumbers(), time()+31556926 ,'/');
		setcookie('_mccss_enable_backup_', enable_backup(), time()+31556926 ,'/');
		setcookie('_mccss_enable_autocomplete_', enable_autocomplete(), time()+31556926 ,'/');
	}
	register_setting('mccss_settings','my_custom_css');
}

// Admin section:
function mycustomcss_admin()
{
	$plugin_page = add_menu_page(__('My Custom CSS Panel','my-custom-css'),__('My Custom CSS','my-custom-css'), 'manage_options', 'my_custom_css', 'mccss_admin_page', mccss_png(), 61);
	add_action('admin_init', 'mycustomcss_registersetting');
	add_action('admin_head-'. $plugin_page, 'mycustomcss_scripts');
}

add_action('admin_menu', 'mycustomcss_admin');
add_action('wp_head', 'mycustomcss_head', 99999);
add_action('admin_print_styles', 'mycustomcss_admin_style');
add_filter('plugin_row_meta', 'add_plugin_meta_links', 10, 2);
add_filter('plugin_action_links_'.plugin_basename(__FILE__).'', 'mycustomcss_links');